name: Docker Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag aspin/fwordle-backend:latest
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: aspin
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push aspin/fwordle-backend:latest

