name: Deploy Backend

on: 
  push:
    branches: [ main, deployment ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v2

    - name: Update Docker
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir -p "$SSH_PATH"

        echo "${{ secrets.BACKEND_SSH_KEY }}" > $SSH_PATH/deploy_key
        chmod 700 "$SSH_PATH"
        chmod 600 "$SSH_PATH/deploy_key"

        ssh -i $HOME/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.BACKEND_USER }}@${{ secrets.BACKEND_HOST }} ./run-backend.sh
